config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  mount Flipflop::Engine => "/flipflop"
  get 'importer_documentation/guide'
  get 'importer_documentation/csv'

  get 'masters/*master_file_path', format: false, to: 'masters#download'

  resources :csv_imports, only: [:index, :show, :new, :create]
  post 'csv_imports/preview', as: 'preview_csv_import'
  get 'csv_imports/preview', to: redirect('csv_imports/new')

  resources :csv_imports, only: [:index, :show, :new, :create]
  get 'csv_imports/:id/log', to: 'csv_imports#log'
  get 'csv_imports/:id/report', to: 'csv_imports#report'

  get 'branding_info/:id', to: 'branding_info#show', as: 'branding_info'

  root 'catalog#index'
  mount Riiif::Engine => 'images', as: :riiif if Hyrax.config.iiif_image_server?
  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'

  mount Qa::Engine => '/authorities'
  mount Hyrax::Engine, at: '/'
  resources :welcome, only: 'index'
  curation_concerns_basic_routes
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/csv_import.rb
# frozen_string_literal: true
class CsvImport < ApplicationRecord
  belongs_to :user
  mount_uploader :manifest, CsvManifestUploader
  delegate :warnings, to: :manifest, prefix: true
  delegate :errors, to: :manifest, prefix: true
  delegate :records, to: :manifest, prefix: true
  has_many :csv_rows
  has_many :csv_collection_reindices
  has_many :csv_import_order_children

  def queue_start_job
    StartCsvImportJob.perform_later(id)
    # TODO: We'll probably need to store job_id on this record.
  end
end

app/controllers/csv_imports_controller.rb
# frozen_string_literal: true

class CsvImportsController < ApplicationController
  load_and_authorize_resource
  before_action :load_and_authorize_preview, only: [:preview]

  with_themed_layout 'dashboard'

  def index; end

  def show
    respond_to do |format|
      format.html do
        @csv_rows = CsvRow.where(csv_import_id: @csv_import.id)
        @min_ingest_duration = min
        @max_ingest_duration = max
        @mean_ingest_duration = mean
        @median_ingest_duration = median
        @standard_deviation_ingest_duration = std_deviation
        @min_ingest_duration = min
      end
      format.csv { send_data service.csv, filename: File.basename(@csv_import.manifest.to_s) }
    end
  end

  def new; end

  # Validate the CSV file and display errors or
  # warnings to the user.
  def preview; end

  def create
    @csv_import.user = current_user
    @csv_import.import_file_path = '/opt/data'
    @csv_import.status = 'queued'
    preserve_cache
    if @csv_import.save
      @csv_import.queue_start_job
      redirect_to @csv_import
    else
      render :new
    end
  end

  def log
    log_file = Rails.root.join('log', "ingest_#{params[:id]}.log")
    log_text = if File.exist?(log_file)
                 File.open(log_file).read
               else
                 'Could not read a log file for this import'
               end
    render plain: log_text
  end

  def service
    @service ||= Californica::CsvImportService.new @csv_import
  end

  private

    def load_and_authorize_preview
      @csv_import = CsvImport.new(create_params)
      authorize! :create, @csv_import
    end

    def create_params
      params.fetch(:csv_import, {}).permit(:manifest, :manifest_records)
    end

    # Since we are re-rendering the form (once for
    # :new and again for :preview), we need to
    # manually set the cache, otherwise the record
    # will lose the manifest file between the preview
    # and the record save.
    def preserve_cache
      return unless params['csv_import']
      @csv_import.manifest_cache = params['csv_import']['manifest_cache']
      @csv_import.record_count = params['csv_import']['record_count']
    end

    def row_times
      @row_times ||= @csv_rows.select('ingest_duration')
    end

    def min
      if @csv_rows.count == @csv_import.record_count
        @min_ingest_duration = row_times.minimum(:ingest_duration)
        @min_ingest_duration&.round(2)
      end
    end

    def max
      if @csv_rows.count == @csv_import.record_count
        @max_ingest_duration = row_times.maximum(:ingest_duration)
        @max_ingest_duration&.round(2)
      end
    end

    def mean
      if @csv_rows.count == @csv_import.record_count
        @mean_ingest_duration = row_times.average(:ingest_duration)
        @mean_ingest_duration&.round(2)
      end
    end

    def median
      if @csv_rows.count == @csv_import.record_count
        @get_ingest_duration_rows = row_times
        durations = @get_ingest_duration_rows.map(&:ingest_duration)
        sorted = durations.compact.sort
        len = sorted.length
        ((sorted[(len - 1) / 2] + sorted[len / 2]) / 2.0).round(2) if len.positive?
      end
    end

    def std_deviation
      if @csv_rows.count == @csv_import.record_count
        durations = row_times.map(&:ingest_duration).compact
        avg = durations.compact.inject { |sum, el| sum + el }.to_f / durations.compact.size
        sd = Math.sqrt(durations.sum { |x| (x - avg)**2 } / @get_ingest_duration_rows.size)
        sd.round(2)
      end
    end
end

app/views/csv_imports/_actions.html.erb
<div class="actions">
  <%= form.submit 'Preview Import',  class: "btn btn-primary btn-lg" %>
</div>

app/views/csv_imports/_error.html.erb
<% if csv_import.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(csv_import.errors.size, "error") %> prohibited this csv_import from being saved:</h2>
    <ul>
      <% csv_import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/csv_imports/_file_upload.html.erb
<%= form.file_field :manifest, required: true, id: 'file-upload', class: "file-upload form-control", onchange: "Californica.displayUploadedFile()" %>
<label for="file-upload" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-upload"></span> Upload Your CSV</label>
<div id="file-upload-display"></div>

app/views/csv_imports/_form.html.erb
<%= form_with(model: csv_import, local: true, html: { multipart: true }, url: preview_csv_import_path) do |form| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-8">
          <h2> Getting Started </h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="well well-lg">
            <p><b>Read the CSV Field Guide</b> to learn what is required in your CSV.</p>
            <div class="text-center">
              <a href="/importer_documentation/guide" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-book"></i> CSV Field Guide</a>
            </div>
          </div>
        </div>
         <div class="col-md-4">
          <div class="well well-lg">
            <p><b>Download a CSV template</b> to get started.</b></p>
            <div class="text-center">
              <a href="/importer_documentation/csv" data-turbolinks="false" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-list"></i> Download a CSV Template</a>            </div>
            </div>
          </div>
        </div>
      <hr/>
      <div class="row">
        <div class="col-md-8">
          <h2> Upload Your CSV </h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="well well-lg">
            <p> <b>Upload a CSV</b> that has your metadata. </p>
            <div class="text-center">
              <%= render "file_upload", form: form  %>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="well well-lg">
            <p> <b>Preview your import</b> before starting the process. </p>
            <div class="text-center">
              <%= render "actions", form: form %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= render "error", csv_import: csv_import %>
        </div>
        <div class="col-md-4">
        </div>
      </div>


      <%= form.hidden_field :manifest_cache %>
<% end %>

app/views/csv_imports/_record_count.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="alert alert-success">
      <p> This import will add <%= @csv_import.manifest_records %>  new records. </p>
    </div>
  </div>
</div>

app/views/csv_imports/_start_import_form.html.erb
<%= form_with(model: csv_import, local: true, html: { multipart: true }) do |form| %>

  <%= form.hidden_field :manifest_cache %>
  <%= form.hidden_field :import_file_path %>
  <%= form.hidden_field :record_count, value: csv_import.manifest_records %>

  <div class="actions">
    <%= form.submit 'Start Import' %>
  </div>
<% end %>

app/views/csv_imports/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-xs-12 main-header">
  <h2>CSV Imports | <small>Time displayed in seconds</small</h2>
</div>

<div class="panel-body">
  <table class="table-condensed table-striped datatable dataTable no-footer" role="grid" data-order="[[ 0, &quot;desc&quot; ]]">
    <thead>
      <tr role="row">
        <th class="sorting_desc">ID</th>
        <th>Created at </th>
        <th>Created by </th>
        <th>Filename </th>
        <th>Record Count </th>
        <th>Status </th>
        <th>Total Time </th>
        <th>Time per Record </th>
      </tr>
    </thead>

    <tbody>
        <% @csv_imports.each do |csv_import| %>
          <tr>
            <% if csv_import&.manifest&.file&.file %>
            <td><%= link_to csv_import.id, csv_import %></td>
            <td><%= csv_import.created_at.in_time_zone("America/Los_Angeles").strftime('%e %b %Y')%><br><%=csv_import.created_at.strftime('%l:%M %p') %></td>
            <td><%= csv_import.user.name  || "Unknown" %></td>
            <td><%= link_to csv_import.manifest.file.file, csv_import %></td>
            <td><%= csv_import.record_count || "Unknown" %></td>
            <td><%= csv_import.status || "Unknown" %></td>
            <td><% if csv_import.elapsed_time %><%= csv_import.elapsed_time.round(3) || "Unknown" %><% end %></td>
            <td><% if csv_import.elapsed_time_per_record %><%= csv_import.elapsed_time_per_record.round(3) ||"Unknown" %><% end %></td>
            <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/csv_imports/new.html.erb
<h2> Import a set of records </h2>
<%= render 'form', csv_import: @csv_import %>

app/views/csv_imports/preview.html.erb
<h2> Preview of your CSV-based Import </h2>

<div id='csv_info'>
  <% if @csv_import.manifest.file %>
    <label> CSV Manifest: </label>
    <%= File.basename(@csv_import.manifest.to_s) %>
  <% end %>
</div>
<% if @csv_import.manifest_errors.empty? %>
<%= render 'record_count', locals: { csv_import: @csv_import } %>
<% else %>
<div class="row">
  <div class="col-md-8">
    <div class="alert alert-danger">
      <p> This import cannot proceed. </p>
      <div id='csv_errors'>
        The CSV file has the following errors:
        <ul>
          <% @csv_import.manifest_errors.each do |error| %>
            <li> <%= error %> </li>
          <% end %>
        </ul>
      </div>
      <p> You will need to correct the errors with the CSV file before you can continue. </p>
      <%= link_to 'Try Again', new_csv_import_path %>
    </div>
  </div>
</div>

<% end %>

<% unless @csv_import.manifest_warnings.empty? %>
  <div id='csv_warnings'>
    The CSV file has the following warnings:
    <ul>
      <% @csv_import.manifest_warnings.each do |warning| %>
        <li> <%= warning %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @csv_import.manifest_errors.empty? %>
  <%= link_to 'Cancel', new_csv_import_path %>
  <br />
  <%= render 'start_import_form', csv_import: @csv_import %>
<% end %>

app/views/csv_imports/show.html.erb
<p id="notice"><%= notice %></p>
<h2>CSV Import <%= @csv_import.id %> <small class='ingest-small'>| <%= File.basename(@csv_import.manifest.to_s) %> | <%= @csv_import.record_count %> queued records | <a href="/csv_imports/<%= @csv_import.id %>/log"> Ingest Log</a> | <a href="/csv_imports/<%= @csv_import.id %>.csv">CSV</a></small></h2>
<h3>Current row count: <%= @csv_rows.count %> | Total record count: <%= @csv_import.record_count %></h3>
<h4 class='ingest-md-gray'>
  <a href="javascript:window.location.href=window.location.href">Refresh page to view updated ingest</a> | Time displayed in seconds
  </h4>
<p>
  <span class='ingest-md-gray'><label> Uploaded by: </label></span>
  <span> <%= @csv_import.user.name %> </span>
</p>

<div class="panel-body">
  <div class="ingest-metrics-table">
    <div class="i-m-table">
      <h4>Full CSV import metrics (<%= @csv_import.record_count %> records)</h4>
      <table class="table-condensed table-striped no-footer ingest-metrics" role="grid">
        <thead>
          <tr role='row'>
            <th> Start time </th>
            <th> Total elapsed time </th>
            <th> Average time per record </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <% if @csv_import.start_time %>
                <%= @csv_import.start_time.in_time_zone("America/Los_Angeles").strftime('%e %b %Y %l:%M %p') %>
              <% else %>
                <span class="ingest-md-gray">n/a</span>
              <% end %>
            </td>
            <td>
              <% if @csv_import.elapsed_time == nil %>
                <span class='ingest-md-gray'>waiting for ingest to finish</span>
              <% else %>
                <%= @csv_import.elapsed_time.round %> s
              <% end %>
            </td>
            <td>
              <% if @csv_import.elapsed_time_per_record == nil %>
                <span class='ingest-md-gray'>waiting for ingest to finish</span>
              <% else %>
                <%= @csv_import.elapsed_time_per_record.round %> s
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <br/>

      <h4>Row ingest metrics (<%= @csv_import.record_count %> records)</h4>
      (Not including reindexing & manifest creation).

      <table class="table-condensed table-striped no-footer ingest-metrics" role="grid">
        <thead>
          <tr role="row">
            <th> Minimum </th>
            <th> Maximum </th>
            <th> Mean </th>
            <th> Median </th>
            <th> Standard deviation </th>
          </tr>
        </thead>
        <tbody>
          <% if @csv_rows.count != @csv_import.record_count %>
           <tr>
            <td colspan='5' class='ingest-md-gray'>Metrics will display after all records have been ingested.</td>
          </tr>
        <% else %>
          <tr>
            <td> <%= @min_ingest_duration %><br/></td>
            <td> <%= @max_ingest_duration || nil %></td>
            <td> <%= @mean_ingest_duration || nil %></td>
            <td> <%= @median_ingest_duration || nil %></td>
            <td> <%= @standard_deviation_ingest_duration || nil %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br/>

<hr class='ingest-hr'>

  <div class="ingest-metrics-table">
  <% Time.zone = "America/Los_Angeles" %>
  <% current_time = Time.current %>
  <h4>Current time: <%= current_time.strftime('%e %b %Y %l:%M:%S:%L %p') %></h4>
    <div class="i-m-table">
      <table class="table-condensed table-striped datatable dataTable no-footer 
      v_logs ingest-metrics" role="grid" data-order="[[ 1, &quot;asc&quot; ]]">
        <thead>
          <tr role="row">
            <th class="sorting_desc">Row&nbsp;#</th>
            <th>Item Ark</th>
            <th>Object Type</th>
            <th>Children</th>
            <th>Last Updated</th>
            <th>Ingest Start</th>
            <th>Ingest End</th>
            <th>Ingest Duration</th>
            <th>Status</th>
            <th>Error message(s)</th>
          </tr>
        </thead>
        <tbody>
          <% @csv_rows.each do |csv_row| %>
            <tr>
              <td><%= csv_row.row_number || "Unknown" %></td>
              <td><%= JSON.parse(csv_row.metadata)["Item ARK"] || "Unknown" %></td>
              <td><%= csv_row.object_type || "Unknown" %></td>
              <td><%= csv_row.no_of_children || "Unknown" %></td>
              <td><%= csv_row.updated_at.strftime('%e %b %Y %l:%M %p') || "Unknown" %></td>
              <% if csv_row.ingest_record_start_time == nil %>
                <td>Unknown</td>
              <% else %>
                <td><%= csv_row.ingest_record_start_time.strftime('%e %b %Y %l:%M:%S:%L %p') || "Unknown" %></td>
              <% end %>
              <% if csv_row.ingest_record_end_time == nil %>
                <td>Unknown</td>
              <% else %>
                <td><%= csv_row.ingest_record_end_time.strftime('%e %b %Y %l:%M:%S:%L %p') || "Unknown" %></td>
              <% end %>
              <% if csv_row.ingest_duration == nil %>
                <td>Unknown</td>
              <% else %>
                <td style='text-align: center'><%= csv_row.ingest_duration.round(3) || "Unknown" %></td>
              <% end %>
              <td><%= csv_row.status || "Unknown" %></td>
              <td><%= csv_row.error_messages || "" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>